---
# tasks file for lb-tier
- name: Install software
  yum:
    name: "{{ _yum_packages }}"
    state: latest

- name: enable haproxy at boot
  service:
    name: haproxy
    enabled: yes

- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
  notify:
  - restart haproxy

- name: enable HAProxy
  service:
    name: haproxy
    state: started
